all: 01 02 03 04 05 06

clean:
	rm -f 01 02 03 04 05 06

01: 01.c
	gcc -o 01 01.c -Wall -Wextra -Werror -O2 -std=c99 -pedantic

02: 02.c
	gcc -o 02 02.c -Wall -Wextra -Werror -O2 -std=c99 -pedantic

03: 03.c
	gcc -o 03 03.c -Wall -Wextra -Werror -O2 -std=c99 -pedantic

04: 04.c
	gcc -o 04 04.c -Wall -Wextra -Werror -O2 -std=c99 -pedantic

05: 05.c
	gcc -o 05 05.c -Wall -Wextra -Werror -O2 -std=c99 -pedantic

06: 06.c
	gcc -o 06 06.c -Wall -Wextra -Werror -O2 -std=c99 -pedantic
