all: 01 02 03

clean:
	rm -f 01 02 03

01: 01.c
	gcc -o 01 01.c -Wall -Wextra -Werror -O2 -std=c99 -pedantic

02: 02.c
	gcc -o 02 02.c -Wall -Wextra -Werror -O2 -std=c99 -pedantic

03: 03.c
	gcc -o 03 03.c -Wall -Wextra -Werror -O2 -std=c99 -pedantic
